#DAILY_STOCK_VIEW
SELECT sy.TIMESTAMP,sy.SYMBOL,
NVL(sy.CLOSE,0) CLOSE,NVL(sy.OPEN,0) OPEN,NVL(sy.LOW,0) LOW,NVL(sy.HIGH,0) HIGH,
NVL(bb.LOWER,0) BB_LOWER,NVL(bb.MIDDLE,0) BB_MIDDLE,NVL(bb.UPPER,0) BB_UPPER,
NVL(ema.VALUE,0) EMA,NVL(wma.VALUE,0) WMA,NVL(dema.VALUE,0) DEMA,NVL(tema.VALUE,0) TEMA,
NVL(trima.VALUE,0) TRIMA,NVL(kama.VALUE,0) KAMA,NVL(t3.VALUE,0) T3,NVL(mama.VALUE_II,0) MAMA_II
FROM DAILY_STOCK sy
LEFT OUTER JOIN BBANDS bb ON bb.DATA=sy.DATA AND bb.SYMBOL=sy.SYMBOL
LEFT OUTER JOIN TEC_IND ema ON ema.DATA=sy.DATA AND ema.SYMBOL=sy.SYMBOL AND ema.IND_TYPE='EMA'
LEFT OUTER JOIN TEC_IND wma ON wma.DATA=sy.DATA AND wma.SYMBOL=sy.SYMBOL AND wma.IND_TYPE='WMA'
LEFT OUTER JOIN TEC_IND dema ON dema.DATA=sy.DATA AND dema.SYMBOL=sy.SYMBOL AND dema.IND_TYPE='DEMA'
LEFT OUTER JOIN TEC_IND tema ON tema.DATA=sy.DATA AND tema.SYMBOL=sy.SYMBOL AND tema.IND_TYPE='TEMA'
LEFT OUTER JOIN TEC_IND trima ON trima.DATA=sy.DATA AND trima.SYMBOL=sy.SYMBOL AND trima.IND_TYPE='TRIMA'
LEFT OUTER JOIN TEC_IND kama ON kama.DATA=sy.DATA AND kama.SYMBOL=sy.SYMBOL AND kama.IND_TYPE='KAMA'
LEFT OUTER JOIN TEC_IND t3 ON t3.DATA=sy.DATA AND t3.SYMBOL=sy.SYMBOL AND t3.IND_TYPE='T3'
LEFT OUTER JOIN TEC_IND_II mama ON mama.DATA=sy.DATA AND mama.SYMBOL=sy.SYMBOL AND mama.IND_TYPE='MAMA'
WHERE sy.CATEGORIA=1 AND sy.DATA>TO_DATE('2000-03-16','YYYY-MM-DD')
ORDER BY sy.DATA ASC;


#ANALIZE_VIEW
SELECT sy.TIMESTAMP,sy.SYMBOL,NVL(sy.CLOSE,0) CLOSE,
NVL(mama.VALUE_I,0) MAMA_I,NVL(mama.VALUE_II,0) MAMA_II,
NVL(sto.VALUE_I,0) STOCHF_I,NVL(sto.VALUE_II,0) STOCHF_II,
NVL(mac.VALUE_I,0) MACDEXT_I,NVL(mac.VALUE_II,0) MACDEXT_II,NVL(mac.VALUE_III,0) MACDEXT_III
FROM DAILY_STOCK sy
LEFT OUTER JOIN TEC_IND_II mama ON mama.DATA=sy.DATA AND mama.SYMBOL=sy.SYMBOL AND mama.IND_TYPE='MAMA'
LEFT OUTER JOIN TEC_IND_II sto ON sto.DATA=sy.DATA AND sto.SYMBOL=sy.SYMBOL AND sto.IND_TYPE='STOCHF'
LEFT OUTER JOIN TEC_IND_III mac ON mac.DATA=sy.DATA AND mac.SYMBOL=sy.SYMBOL AND mac.IND_TYPE='MACDEXT'
WHERE sy.CATEGORIA=1 AND sy.SYMBOL='ENEL.MI' AND sy.DATA>TO_DATE('2000-03-16','YYYY-MM-DD')
ORDER BY sy.DATA ASC;